files:
  - source: /src/main/resources/assets/minecolonies/lang/en_us.lang
    translation: /src/main/resources/assets/minecolonies/lang/%locale_with_underscore%.lang
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_AZ
        be: be_BY
        bg: bg_BG
        br-FR: br_FR
        ca: ca_ES
        cs: cs_CZ
        cy: cy_GB
        da: da_DK
        de-AT: de_AT
        de: de_DE
        el: el_GR
        en-AU: en_AU
        en-CA: en_CA
        en-GB: en_GB
        en-NZ: en_NZ
        en-UD: en_UD
        en-PT: en_7S
        eo: eo_UY
        es-AR: es_AR
        es-MX: es_MX
        es-UY: es_UY
