files:
  - source: /src/main/resources/assets/minecolonies/lang/en_us.lang
    translation: /src/main/resources/assets/minecolonies/lang/%locale_with_underscore%.lang
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_AZ
        be: be_BY
        bg: bg_BG
        br-FR: br_FR
        ca: ca_ES
        cs: cs_CZ
        cy: cy_GB
        da: da_DK
        de-AT: de_AT
        de: de_DE
        el: el_GR
        en-AU: en_AU
        en-CA: en_CA
        en-GB: en_GB
        en-NZ: en_NZ
        en-UD: en_UD
        en-PT: en_7S
        eo: eo_UY
        es-AR: es_AR
        es-MX: es_MX
        es-UY: es_UY
        es-VE: es_VE
        et: et_EE
        eu: eu_ES
        fa: fa_IR
        fi: fi_FI
        fil: tl_PH
        fo: fo_FO
        fr: fr_FR
        fr-CA: fr_CA
        fy-NL: fy_NL
        ga-IE: ga_IE
        gd: gd_GB
        gl: gl_ES
        gv: gv_IM
        haw: haw
        he: he_IL
        hi: hi_IN
        hr: hr_HR
        hu: hu_HU
        hy-AM: hy_AM
        id: id_ID
        is: is_IS
        ido: io
        it: it_IT
        ja: ja_JP
        jbo: jbo_EN
        ka: ka_GE
        ko: ko_KR
        kw: kw_GB
        la-LA: la_VA
        lb: lb_LU
        li: li_LI
        lol: lol_US
        lt: lt_LT
        lv: lv_LV
        mi: mi_NZ
        mk: mk_MK
        mn: mn_MN
        ms: ms_MY
        mt: mt_MT
        nds: nds_DE
        nl: nl_NL
        nn-NO: nn_NO
        no: no_NO
        oc: oc_FR
        pl: pl_PL
        pt-BR: pt_BR
        pt-PT: pt_PT
        qya-AA: qya_AA
        ro: ro_RO
        ru: ru_RU
        se: sme
        sk: sk_SK
        sl: sl_SI
        so: so_SO
        sq: sq_AL
        sr: sr_SP
        sv-SE: sv_SE
        th: th_TH
        tlh-AA: tlh_AA
        tr: tr_TR
        tzl: tzl_TZL
        uk: uk_UA
        val-ES: ca-val_ES
        vi: vi_VN
        zh-CN: zh_CN
        zh-TW: zh_TW
