files:
  - source: /src/main/resources/assets/minecolonies/lang/en_us.lang
    translation: /src/main/resources/assets/minecolonies/lang/%locale_with_underscore%.lang
    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_AZ
        be: be_BY
        bg: bg_BG
        br-FR: br_FR
        ca: ca_ES
        cs: cs_CZ
        cy: cy_GB
        da: da_DK
        de-AT: de_AT
        de: de_DE
        el: el_GR
        en-AU: en_AU
        en-CA: en_CA
        en-GB: en_GB
        en-NZ: en_NZ
        en-UD: en_UD
        en-PT: en_7S
        eo: eo_UY
        es-AR: es_AR
        es-MX: es_MX
        es-UY: es_UY
        es-VE: es_VE
        et: et_EE
        eu: eu_ES
        fa: fa_IR
        fi: fi_FI
        fil: fil_PH
        fo: fo_FO
        fr: fr_FR
        fr-CA: fr_CA
        fy-NL: fy_NL
        ga-IE: ga_IE
        gd: gd_GB
        gl: gl_ES
        gv: gv_IM
        haw: haw
        he: he_IL
        hi: hi_IN
        hr: hr_HR
        hu: hu_HU
        hy-AM: hy_AM
        id: id_ID
        is: is_IS
        ido: io
        it: it_IT
        ja: ja_JP
        jbo: jbo_EN
        ka: ka_GE
        ko: ko_KR
        kw: kw_GB
        la-LA: la_VA
        lb: lb_LU
        li: li_LI
        lol: lol_US
        lt: lt_LT
        lv: lv_LV
